CUDA_VISIBLE_DEVICES="0,1" python train.py \
	--model_dir "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext" \
	--train_dir "/home/fierens/Researcher/hierarchical-sapbert/data/training_file/training_file_translation_fr_smart_uncased_no_dup_pairwise_pair_th50.txt" \
	--output_dir tmp/sapbert-freng-smart\
	--use_cuda \
	--epoch 1 \
	--train_batch_size 256 \
	--learning_rate 2e-5 \
	--max_length 25 \
	--checkpoint_step 999999 \
	--parallel \
	--amp \
	--pairwise \
	--random_seed 33 \
	--loss ms_loss \
	--use_miner \
	--type_of_triplets "all" \
	--miner_margin 0.2 \
	--agg_mode "cls"
